spring:
  application:
    name: msclientes

  datasource:
    url: jdbc:mysql://localhost:3306/clientes?createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=America/Sao_Paulo
    username: root
    password: 2024@@2024
    driver-class-name: com.mysql.jdbc.Driver
    test-while-idle: true
    validation-query: SELECT 1
    hikari:
      maximum-pool-size: 5
      minimum-idle: 3
      idle-timeout: 10000

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

  mvc:
    throw-exception-if-no-handler-found: true

  web:
    resources:
      add-mappings: false

  jackson:
    deserialization:
      fail-on-ignored-properties: true
      fail-on-unknown-properties: true

  flyway:
    locations: classpath:db/migration,classpath:db/testsdata
    baseline-on-migrate: true

server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
